# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"

  - script: |
      pip --version
      pip install numpy scipy matplotlib jupytext nbconvert jupyter_client
    displayName: "Install dependencies"

  - script: |
      python conf/convert_to_ipynb.py notebooks built_notebooks
    displayName: "Test and convert notebooks"
