# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      pip --version
      pip install numpy scipy matplotlib jupytext nbconvert
    displayName: "Install dependencies"

  - script: |
      python conf/convert_to_ipynb.py notebooks built_notebooks
    displayName: "Test and convert notebooks"
